# Generated by Django 4.2.7 on 2025-09-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0002_update_indexing_job_schema_for_api_compliance'),
    ]

    operations = [
        # Create proper indexes and constraints for shared table
        migrations.RunSQL(
            # Forward migration
            sql="""
                -- Wait for table to be created by previous migrations, then add indexes
                DO $$ 
                BEGIN
                    -- Only proceed if the table exists
                    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'indexing_indexingjob') THEN
                        -- Create indexes for performance
                        CREATE INDEX IF NOT EXISTS idx_indexing_jobs_org_id ON indexing_indexingjob(org_id);
                        CREATE INDEX IF NOT EXISTS idx_indexing_jobs_site_id ON indexing_indexingjob(site_id);
                        CREATE INDEX IF NOT EXISTS idx_indexing_jobs_status ON indexing_indexingjob(status);
                        CREATE INDEX IF NOT EXISTS idx_indexing_jobs_external_job_id ON indexing_indexingjob(external_job_id);
                        CREATE INDEX IF NOT EXISTS idx_indexing_jobs_created_at ON indexing_indexingjob(created_at);

                        -- Create unique constraint for idempotency (org_id + external_job_id)
                        CREATE UNIQUE INDEX IF NOT EXISTS uq_indexing_jobs_org_external_django 
                        ON indexing_indexingjob(org_id, external_job_id) 
                        WHERE external_job_id IS NOT NULL AND external_job_id != '';
                    END IF;
                END $$;
            """,
            # Reverse migration
            reverse_sql="""
                DROP INDEX IF EXISTS idx_indexing_jobs_org_id;
                DROP INDEX IF EXISTS idx_indexing_jobs_site_id; 
                DROP INDEX IF EXISTS idx_indexing_jobs_status;
                DROP INDEX IF EXISTS idx_indexing_jobs_external_job_id;
                DROP INDEX IF EXISTS idx_indexing_jobs_created_at;
                DROP INDEX IF EXISTS uq_indexing_jobs_org_external_django;
            """
        ),
    ]
