# Generated by Django 4.2.7 on 2025-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0004_remove_indexingjob_uq_indexing_jobs_tenant_external_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indexingjob',
            name='uq_indexing_jobs_tenant_external',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='indexing_jo_org_id_b52753_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='indexing_jo_org_id_51c02a_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='indexing_jo_status_15b1ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='indexing_jo_webhook_a5a5bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='indexing_jo_complet_3a7b9b_idx',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='allowed_domains',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='callback_url',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='custom_config',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='embed_model',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='excluded_subdomains',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='namespace_override',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='namespace_prefix',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='phase1_result',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='phase2_result',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='pinecone_index',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='requested_by_user_id',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='requested_params',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='streaming_mode',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='use_namespaces',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='webhook_attempts',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='webhook_last_attempt_at',
        ),
        migrations.RemoveField(
            model_name='indexingjob',
            name='webhook_status',
        ),
        migrations.AddConstraint(
            model_name='indexingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('external_job_id__isnull', False)), fields=('external_job_id',), name='uq_indexing_jobs_external_id'),
        ),
    ]
