# Generated by Django 4.2.7 on 2025-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0005_remove_indexingjob_uq_indexing_jobs_tenant_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexingjob',
            name='org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
