# Generated by Django 4.2.7 on 2025-12-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0101_remove_indexingjob_idx_job_site_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_site_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_site_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_external_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_task_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_active_created_idx',
        ),
        migrations.RenameIndex(
            model_name='indexingjob',
            new_name='indexing_jobs_org_status_idx',
            old_name='idx_job_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='indexingjob',
            new_name='indexing_jobs_org_created_idx',
            old_name='idx_job_org_created_idx',
        ),
    ]
