# Generated by Django 4.2.7 on 2025-12-22 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawa_auth', '0003_apikey_expires_at_apikey_api_keys_expires_f68b1a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('indexing_notifications', models.BooleanField(default=True, help_text='Notifications when indexing completes')),
                ('chatbot_notifications', models.BooleanField(default=True, help_text='Notifications about chatbot activity')),
                ('weekly_digest', models.BooleanField(default=True, help_text='Receive weekly summary emails')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='Preferred UI theme', max_length=10)),
                ('language', models.CharField(default='en', help_text='Preferred language', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='User timezone', max_length=50)),
                ('enable_analytics', models.BooleanField(default=True, help_text='Enable analytics tracking')),
                ('enable_tooltips', models.BooleanField(default=True, help_text='Show helpful tooltips')),
                ('compact_mode', models.BooleanField(default=False, help_text='Use compact UI mode')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Has completed onboarding')),
                ('tour_completed', models.BooleanField(default=False, help_text='Has completed product tour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
