# Generated by Django 4.2.7 on 2025-12-22 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lawa_auth', '0004_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField(blank=True, help_text='Organization context if applicable', null=True)),
                ('rating', models.CharField(choices=[('poor', 'Poor'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], help_text='Overall experience rating', max_length=20)),
                ('comments', models.TextField(help_text='User comments and suggestions')),
                ('allow_contact', models.BooleanField(default=False, help_text='User allows follow-up contact')),
                ('page_url', models.CharField(blank=True, help_text='Page where feedback was submitted', max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent', max_length=500, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_feedba_user_id_3f1202_idx'), models.Index(fields=['org_id'], name='user_feedba_org_id_5b7824_idx'), models.Index(fields=['status'], name='user_feedba_status_748f20_idx'), models.Index(fields=['created_at'], name='user_feedba_created_1f96f0_idx')],
            },
        ),
    ]
