# Generated by Django 4.2.7 on 2026-01-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
    ]
