# Generated by Django 4.2.7 on 2025-09-08 12:50

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField()),
                ('domain', models.CharField(max_length=255, validators=[django.core.validators.URLValidator()])),
                ('verification_method', models.CharField(choices=[('dns', 'DNS'), ('file', 'File')], default='dns', max_length=10)),
                ('verification_token', models.CharField(max_length=255, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('pinecone_index', models.CharField(blank=True, max_length=255)),
                ('namespace_override', models.CharField(blank=True, max_length=255)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'sites',
                'indexes': [models.Index(fields=['org_id'], name='sites_org_id_fa5ae0_idx'), models.Index(fields=['domain'], name='sites_domain_27d5c3_idx'), models.Index(fields=['status'], name='sites_status_2d6a2c_idx'), models.Index(fields=['verification_token'], name='sites_verific_35e626_idx')],
                'unique_together': {('org_id', 'domain')},
            },
        ),
    ]
