# Generated by Django 4.2.7 on 2025-12-22 10:02

from django.db import migrations


def migrate_indexes(apps, schema_editor):
    """Safely handle index migration."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Remove old indexes if they exist
            indexes_to_remove = [
                'site_status_indexed_idx',
                'site_domain_idx',
                'site_active_namespace_idx',
            ]
            for index_name in indexes_to_remove:
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")

            # Handle org_status index
            cursor.execute("""
                SELECT indexname FROM pg_indexes
                WHERE tablename = 'sites'
                AND indexname = 'site_org_status_idx'
            """)
            if cursor.fetchone():
                cursor.execute("""
                    ALTER INDEX site_org_status_idx
                    RENAME TO sites_org_status_idx
                """)
            else:
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS sites_org_status_idx
                    ON sites (org_id, status)
                """)

            # Handle org_created index
            cursor.execute("""
                SELECT indexname FROM pg_indexes
                WHERE tablename = 'sites'
                AND indexname = 'site_org_created_idx'
            """)
            if cursor.fetchone():
                cursor.execute("""
                    ALTER INDEX site_org_created_idx
                    RENAME TO sites_org_created_idx
                """)
            else:
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS sites_org_created_idx
                    ON sites (org_id, created_at)
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0100_add_performance_indexes'),
    ]

    operations = [
        migrations.RunPython(
            migrate_indexes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
