# Generated by Django 4.2.7 on 2025-12-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0101_remove_site_site_status_indexed_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='site',
            name='site_status_indexed_idx',
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='site_domain_idx',
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='site_active_namespace_idx',
        ),
        migrations.RenameIndex(
            model_name='site',
            new_name='sites_org_status_idx',
            old_name='site_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='site',
            new_name='sites_org_created_idx',
            old_name='site_org_created_idx',
        ),
    ]
