# Generated by Django 5.1.6 on 2026-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0104_add_excluded_url_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('domain', 'org_id'), name='unique_site_domain_per_org'),
        ),
    ]
