# Generated by Django 4.2.7 on 2025-09-08 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('indexing_update', 'Indexing Update')], max_length=20)),
                ('target_url', models.URLField()),
                ('payload', models.JSONField(default=dict)),
                ('result_status', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhook_events',
                'indexes': [models.Index(fields=['kind'], name='webhook_eve_kind_63cc07_idx'), models.Index(fields=['result_status'], name='webhook_eve_result__7dac65_idx'), models.Index(fields=['created_at'], name='webhook_eve_created_8fa52f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField()),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['org_id'], name='audit_logs_org_id_74e940_idx'), models.Index(fields=['actor_user_id'], name='audit_logs_actor_u_6a2681_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
