# Generated by Django 4.2.7 on 2025-12-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['org_id', 'created_at'], name='audit_logs_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['org_id', 'action'], name='audit_logs_org_action_idx'),
        ),
    ]
