# Generated by Django 4.2.7 on 2025-12-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='site',
            name='sites_org_id_fa5ae0_idx',
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='sites_verific_35e626_idx',
        ),
        # migrations.AlterUniqueTogether(
        #     name='site',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='site',
            name='active_namespace',
            field=models.CharField(blank=True, help_text='Currently active Pinecone namespace', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        # migrations.RemoveField(
        #     model_name='site',
        #     name='namespace_override',
        # ),
        # migrations.RemoveField(
        #     model_name='site',
        #     name='org_id',
        # ),
        # migrations.RemoveField(
        #     model_name='site',
        #     name='pinecone_index',
        # ),
        # migrations.RemoveField(
        #     model_name='site',
        #     name='verification_method',
        # ),
        # migrations.RemoveField(
        #     model_name='site',
        #     name='verification_token',
        # ),
        # migrations.RemoveField(
        #     model_name='site',
        #     name='verified_at',
        # ),
    ]
