# Generated by Django 4.2.7 on 2025-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_site_sites_org_id_fa5ae0_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='site',
            name='org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='site',
            name='namespace_override',
        ),
        migrations.RemoveField(
            model_name='site',
            name='pinecone_index',
        ),
        migrations.RemoveField(
            model_name='site',
            name='verification_method',
        ),
        migrations.RemoveField(
            model_name='site',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='site',
            name='verified_at',
        ),
    ]
