# Generated by Django 4.2.7 on 2025-12-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_unique_together_alter_site_org_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='org_id',
        ),
    ]
