# Generated by Django 6.0 on 2025-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_site_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, help_text='Project/Site name', max_length=255),
        ),
    ]
