# Generated by Django 4.2.7 on 2025-12-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_add_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('indexing', 'Indexing')], default='active', max_length=20),
        ),
    ]
