# Generated by Django 4.2.7 on 2025-12-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0102_remove_site_site_status_indexed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='crawl_delay',
            field=models.FloatField(default=1.0, help_text='Delay between page requests in seconds'),
        ),
        migrations.AddField(
            model_name='site',
            name='enable_dynamic_content',
            field=models.BooleanField(default=False, help_text='Handle infinite scroll and dynamic content'),
        ),
        migrations.AddField(
            model_name='site',
            name='enable_javascript',
            field=models.BooleanField(default=True, help_text='Enable JavaScript rendering'),
        ),
        migrations.AddField(
            model_name='site',
            name='enable_pdf_processing',
            field=models.BooleanField(default=True, help_text='Process PDF files'),
        ),
        migrations.AddField(
            model_name='site',
            name='include_subdomains',
            field=models.BooleanField(default=False, help_text='Include subdomains in crawl'),
        ),
        migrations.AddField(
            model_name='site',
            name='indexed_pages_count',
            field=models.IntegerField(default=0, help_text='Number of pages indexed'),
        ),
        migrations.AddField(
            model_name='site',
            name='indexing_config',
            field=models.JSONField(blank=True, default=dict, help_text='Indexing configuration settings'),
        ),
        migrations.AddField(
            model_name='site',
            name='max_pages',
            field=models.IntegerField(default=100, help_text='Maximum pages to crawl'),
        ),
        migrations.AddField(
            model_name='site',
            name='respect_robots',
            field=models.BooleanField(default=True, help_text='Respect robots.txt rules'),
        ),
        migrations.AddField(
            model_name='site',
            name='scrape_all_subdomains',
            field=models.BooleanField(default=False, help_text='Auto-discover and scrape all subdomains'),
        ),
        migrations.AddField(
            model_name='site',
            name='total_documents',
            field=models.IntegerField(default=0, help_text='Total documents in vector store'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('indexing', 'Indexing'), ('failed', 'Failed')], default='active', max_length=20),
        ),
    ]
