# Generated by Django 4.2.7 on 2025-12-28 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0103_add_indexing_config_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedURLPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.UUIDField(db_index=True, help_text='Site to apply exclusion to')),
                ('org_id', models.UUIDField(blank=True, db_index=True, help_text='Organization context', null=True)),
                ('pattern', models.CharField(help_text='URL pattern to exclude', max_length=2000)),
                ('pattern_type', models.CharField(choices=[('exact', 'Exact Match'), ('prefix', 'Prefix Match'), ('suffix', 'Suffix Match'), ('contains', 'Contains'), ('regex', 'Regular Expression')], default='prefix', help_text='How to match the pattern', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Description or reason for exclusion', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this exclusion is currently active')),
                ('urls_matched', models.IntegerField(default=0, help_text='Number of URLs matched by this pattern in last indexing')),
            ],
            options={
                'verbose_name': 'Excluded URL Pattern',
                'verbose_name_plural': 'Excluded URL Patterns',
                'db_table': 'excluded_url_patterns',
                'indexes': [models.Index(fields=['site_id', 'is_active'], name='excluded_ur_site_id_049bfa_idx'), models.Index(fields=['org_id', 'site_id'], name='excluded_ur_org_id_4ed5f9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='excludedurlpattern',
            constraint=models.UniqueConstraint(fields=('site_id', 'pattern', 'pattern_type'), name='uq_excluded_pattern_per_site'),
        ),
    ]
