# Generated by Django 5.1.6 on 2026-01-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0105_alter_site_domain_site_unique_site_domain_per_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, help_text='Knowledge Base name', max_length=255),
        ),
    ]
