# Generated by Codex on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0106_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='verification_method',
            field=models.CharField(choices=[('dns', 'DNS'), ('file', 'File')], default='dns', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='verification_mode',
            field=models.CharField(choices=[('required', 'Required'), ('public', 'Public')], default='required', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='public_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
