# Generated by Django 5.1.6 on 2026-01-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_leadscore_llm_insights'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadscore',
            new_name='lead_scores_org_id_c1a4e8_idx',
            old_name='lead_scores_org_id_session_idx',
        ),
        migrations.RenameIndex(
            model_name='leadscore',
            new_name='lead_scores_org_id_577398_idx',
            old_name='lead_scores_org_id_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='leadscore',
            new_name='lead_scores_chatbot_8af4b3_idx',
            old_name='lead_scores_chatbot_date_idx',
        ),
        migrations.RenameIndex(
            model_name='leadscore',
            new_name='lead_scores_detecte_18b8a8_idx',
            old_name='lead_scores_intent_idx',
        ),
        migrations.RenameIndex(
            model_name='leadscore',
            new_name='lead_scores_total_s_7b0615_idx',
            old_name='lead_scores_total_score_idx',
        ),
        migrations.RenameIndex(
            model_name='leadscore',
            new_name='lead_scores_session_2b08a0_idx',
            old_name='lead_scores_date_score_idx',
        ),
        migrations.RenameIndex(
            model_name='reportpreferences',
            new_name='report_pref_weekly__3771b2_idx',
            old_name='report_prefs_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='reportpreferences',
            new_name='report_pref_report__ce2b4c_idx',
            old_name='report_prefs_schedule_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyleadsreport',
            new_name='weekly_lead_org_id_783063_idx',
            old_name='weekly_reports_org_week_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyleadsreport',
            new_name='weekly_lead_user_id_63a143_idx',
            old_name='weekly_reports_user_week_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyleadsreport',
            new_name='weekly_lead_email_s_e4a4d5_idx',
            old_name='weekly_reports_email_sent_idx',
        ),
        migrations.AlterField(
            model_name='weeklyleadsreport',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Detailed report data structure:\n        {\n            "top_leads": [{id, priority, intent, score, questions, geo, device, date}],\n            "intent_breakdown": {"pricing": 10, "demo": 5, ...},\n            "geo_distribution": {"US": 50, "UK": 20, ...},\n            "device_breakdown": {"desktop": 60, "mobile": 35, "tablet": 5},\n            "daily_trend": [{"date": "2025-01-13", "count": 10}, ...],\n            "top_questions": ["How much does it cost?", ...],\n            "peak_hours": {"9": 15, "10": 20, ...},\n            "avg_session_duration": 180,\n            "avg_messages_per_session": 5.2,\n            "feedback_summary": {"positive": 20, "negative": 5, "none": 75}\n        }\n        '),
        ),
    ]
