# Generated by Django 5.2.6 on 2025-09-27 23:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike'), ('no_feedback', 'No Feedback')], default='no_feedback', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Chat Feedback',
                'verbose_name_plural': 'Chat Feedbacks',
                'db_table': 'chat_feedbacks',
                'indexes': [models.Index(fields=['message'], name='chat_feedba_message_204c1e_idx'), models.Index(fields=['feedback_type'], name='chat_feedba_feedbac_5e5f94_idx'), models.Index(fields=['user_id'], name='chat_feedba_user_id_2f535f_idx'), models.Index(fields=['created_at'], name='chat_feedba_created_09c6ca_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('message', 'user_id'), name='unique_user_feedback_per_message'), models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False), ('user_id__isnull', True)), fields=('message', 'ip_address'), name='unique_anonymous_feedback_per_message')],
            },
        ),
    ]
