# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_feedback_chatfeedback'),
    ]

    operations = [
        # Add new fields to match chatbot backend structure
        migrations.AddField(
            model_name='chatsession',
            name='session_data',
            field=models.JSONField(default=dict, help_text='Session metadata and context'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='ended_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('ended', 'Ended'),
                    ('timeout', 'Timeout'),
                ],
                default='active',
                max_length=20
            ),
        ),
    ]