# Generated by Django 4.2.7 on 2025-12-18 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatbot_chatbots_org_id_a5fd6e_idx_and_more'),
        ('sites', '0002_remove_site_sites_org_id_fa5ae0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_add_session_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_chatbot_15800d_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_site_id_39b307_idx',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='chatbot_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chatbot.chatbot'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='sites.site'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='org_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['site'], name='chat_sessio_site_id_39b307_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chatbot'], name='chat_sessio_chatbot_15800d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user'], name='chat_sessio_user_id_54b88f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status'], name='chat_sessio_status_f6889c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['started_at'], name='chat_sessio_started_c8e10e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['last_activity'], name='chat_sessio_last_ac_699eab_idx'),
        ),
    ]
