# Generated by Django 4.2.7 on 2025-12-22 10:02

from django.db import migrations


def remove_indexes_if_exist(apps, schema_editor):
    """Safely remove indexes only if they exist."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            indexes_to_remove = [
                'chat_feedback_msg_created_idx',
                'chat_feedback_msg_user_created_idx',
                'chat_feedback_type_created_idx',
                'chat_msg_sess_created_idx',
                'chat_msg_sess_role_created_idx',
                'chat_msg_created_idx',
                'chat_sess_org_status_idx',
                'chat_sess_org_created_idx',
                'chat_sess_bot_created_idx',
                'chat_sess_site_created_idx',
                'chat_sess_user_created_idx',
                'chat_sess_status_activity_idx',
            ]
            for index_name in indexes_to_remove:
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0100_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.RunPython(
            remove_indexes_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
