# Generated by Django 4.2.7 on 2026-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0104_rename_chat_messag_category_idx_chat_messag_query_c_82a675_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_turn',
            field=models.IntegerField(blank=True, help_text='Turn number in the conversation (1-indexed)', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='device_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], help_text='Device type detected from user agent', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='referrer',
            field=models.URLField(blank=True, help_text='Page referrer URL for traffic source analytics', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation_turn'], name='chat_messag_convers_41b770_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['device_type'], name='chat_sessio_device__6b3a23_idx'),
        ),
    ]
