# Generated by Django 5.1.6 on 2026-01-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0105_chatmessage_conversation_turn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatfeedback',
            name='comment',
        ),
    ]
