# Generated by Django 4.2.7 on 2025-09-08 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField()),
                ('site_id', models.UUIDField()),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('external_job_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('requested_by_user_id', models.UUIDField()),
                ('callback_url', models.URLField(blank=True)),
                ('requested_params', models.JSONField(default=dict)),
                ('phase1_result', models.JSONField(blank=True, default=dict)),
                ('phase2_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Indexing Job',
                'verbose_name_plural': 'Indexing Jobs',
                'db_table': 'indexing_jobs',
                'indexes': [models.Index(fields=['org_id'], name='indexing_jo_org_id_b52753_idx'), models.Index(fields=['site_id'], name='indexing_jo_site_id_f4f490_idx'), models.Index(fields=['status'], name='indexing_jo_status_b1a5a3_idx'), models.Index(fields=['external_job_id'], name='indexing_jo_externa_2fbcc1_idx'), models.Index(fields=['created_at'], name='indexing_jo_created_f4c9f6_idx')],
            },
        ),
    ]
