# Generated by Django 4.2.7 on 2025-09-15 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexingjob',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, help_text='Additional allowed domains'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='custom_config',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form configuration overrides'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='documents_indexed',
            field=models.IntegerField(default=0, help_text='Number of documents indexed'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='embed_model',
            field=models.CharField(blank=True, help_text='Embedding model to use', max_length=255),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='excluded_subdomains',
            field=models.JSONField(blank=True, default=list, help_text='Subdomains to skip'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='max_pages',
            field=models.IntegerField(default=100, help_text='Maximum pages to collect'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='namespace_override',
            field=models.TextField(blank=True, help_text='Explicit namespace to use'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='namespace_prefix',
            field=models.CharField(default='website_domain', help_text='Domain-based namespace prefix', max_length=255),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='pinecone_index',
            field=models.CharField(blank=True, help_text='Target Pinecone index name', max_length=255),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='streaming_mode',
            field=models.BooleanField(default=True, help_text='Enable streaming mode'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='url',
            field=models.TextField(default='', help_text='URL to be indexed', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='urls_collected',
            field=models.IntegerField(default=0, help_text='Number of URLs collected'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='urls_processed',
            field=models.IntegerField(default=0, help_text='Number of URLs processed'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='use_namespaces',
            field=models.BooleanField(default=True, help_text='Enable Pinecone namespaces'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='webhook_attempts',
            field=models.IntegerField(default=0, help_text='Number of webhook delivery attempts'),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='webhook_last_attempt_at',
            field=models.DateTimeField(blank=True, help_text='Last webhook attempt timestamp', null=True),
        ),
        migrations.AddField(
            model_name='indexingjob',
            name='webhook_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], help_text='Webhook delivery status', max_length=32),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='callback_url',
            field=models.URLField(blank=True, help_text='Webhook callback URL'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When job completed', null=True),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if job failed'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='external_job_id',
            field=models.CharField(help_text='Idempotent job ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='org_id',
            field=models.UUIDField(help_text='Organization/tenant identifier'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='phase1_result',
            field=models.JSONField(blank=True, default=dict, help_text='Phase 1 (URL collection) results'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='phase2_result',
            field=models.JSONField(blank=True, default=dict, help_text='Phase 2 (indexing) results'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='requested_by_user_id',
            field=models.UUIDField(help_text='User who requested the job'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='requested_params',
            field=models.JSONField(default=dict, help_text='Original request parameters (legacy)'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='site_id',
            field=models.UUIDField(help_text='Site identifier within tenant'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When job started processing', null=True),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('collecting_urls', 'Collecting URLs'), ('processing_urls', 'Processing URLs'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', help_text='Current job status', max_length=20),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='task_id',
            field=models.CharField(blank=True, help_text='External service task ID', max_length=255),
        ),
        migrations.AddIndex(
            model_name='indexingjob',
            index=models.Index(fields=['task_id'], name='indexing_jo_task_id_4a8c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='indexingjob',
            index=models.Index(fields=['org_id', 'external_job_id'], name='indexing_jo_org_id_51c02a_idx'),
        ),
        migrations.AddIndex(
            model_name='indexingjob',
            index=models.Index(fields=['status', 'created_at'], name='indexing_jo_status_15b1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='indexingjob',
            index=models.Index(fields=['webhook_status'], name='indexing_jo_webhook_a5a5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='indexingjob',
            index=models.Index(fields=['completed_at'], name='indexing_jo_complet_3a7b9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='indexingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('external_job_id__isnull', False)), fields=('org_id', 'external_job_id'), name='uq_indexing_jobs_tenant_external'),
        ),
    ]
