# Generated by Django 4.2.7 on 2025-12-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0003_auto_20250925_1704'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='indexingjob',
        #     name='uq_indexing_jobs_tenant_external',
        # ),
        # ... (Legacy cleanup skipped due to simplified DB state)
        # migrations.RemoveField(
        #     model_name='indexingjob',
        #     name='webhook_status',
        # ),
        migrations.AddField(
            model_name='indexingjob',
            name='target_namespace',
            field=models.CharField(blank=True, help_text='Namespace being populated by this job', max_length=255),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='site_id',
            field=models.UUIDField(help_text='Site identifier'),
        ),
        migrations.AlterField(
            model_name='indexingjob',
            name='url',
            field=models.TextField(help_text='URL to be indexed'),
        ),
        # migrations.AddConstraint(
        #     model_name='indexingjob',
        #     constraint=models.UniqueConstraint(condition=models.Q(('external_job_id__isnull', False)), fields=('external_job_id',), name='uq_indexing_jobs_external_id'),
        # ),
    ]
