# Generated by Django 4.2.7 on 2025-12-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0006_indexingjob_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexingjob',
            name='org_id',
        ),
    ]
