# Generated by Django 4.2.7 on 2025-12-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0007_remove_indexingjob_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexingjob',
            name='org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
