# Generated by Django 4.2.7 on 2025-12-28 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0103_add_callback_url_and_phase_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.UUIDField(db_index=True, help_text='Site identifier')),
                ('indexing_job_id', models.UUIDField(db_index=True, help_text='Indexing job that processed this page')),
                ('org_id', models.UUIDField(blank=True, db_index=True, help_text='Organization identifier', null=True)),
                ('url', models.URLField(help_text='Full URL of the indexed page', max_length=2000)),
                ('url_hash', models.CharField(db_index=True, help_text='SHA256 hash of URL for fast lookups', max_length=64)),
                ('title', models.CharField(blank=True, help_text='Page title', max_length=500)),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('other', 'Other')], default='html', help_text='Type of content', max_length=50)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('queued', 'Queued'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='discovered', help_text='Current processing status', max_length=20)),
                ('document_count', models.IntegerField(default=0, help_text='Number of chunks/documents created')),
                ('content_size_bytes', models.IntegerField(default=0, help_text='Size of extracted content in bytes')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='When URL was discovered')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('user_added', models.BooleanField(default=False, help_text='Manually added by user')),
            ],
            options={
                'verbose_name': 'Indexed Page',
                'verbose_name_plural': 'Indexed Pages',
                'db_table': 'indexed_pages',
                'indexes': [models.Index(fields=['site_id', 'status'], name='indexed_pag_site_id_40d459_idx'), models.Index(fields=['indexing_job_id', 'status'], name='indexed_pag_indexin_521b1e_idx'), models.Index(fields=['url_hash'], name='indexed_pag_url_has_99ce9d_idx'), models.Index(fields=['org_id', 'site_id'], name='indexed_pag_org_id_81e554_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='indexedpage',
            constraint=models.UniqueConstraint(fields=('site_id', 'url_hash'), name='uq_indexed_pages_site_url'),
        ),
    ]
