# Generated by Django on 2026-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0104_add_indexed_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexingjob',
            name='pages_indexed',
            field=models.IntegerField(default=0, help_text='Number of pages successfully indexed'),
        ),
    ]
