# Generated by Django 4.2.27 on 2026-01-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0105_add_indexing_job_pages_indexed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_site_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_site_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_external_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_task_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexingjob',
            name='idx_job_active_created_idx',
        ),
        # migration.RenameIndex is not idempotent if the old index is missing.
        # We replace it with RunPython/RunSQL to handle missing indexes gracefully.
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'idx_job_org_status_idx' AND n.nspname = current_schema()) THEN
                    ALTER INDEX idx_job_org_status_idx RENAME TO indexing_jobs_org_status_idx;
                ELSIF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'indexing_jobs_org_status_idx' AND n.nspname = current_schema()) THEN
                    -- Neither old nor new exists, likely implies we should create it or it will be created by a future AddIndex?
                    -- But RenameIndex suggests it was defined in Meta. 
                    -- Let's purely try to rename if old exists, otherwise assume new one might need creation or is already there.
                    -- Safety: If old doesn't exist, we do nothing. The model state in Django will update index name, 
                    -- and if the DB lacks it, a future makemigrations might suggest adding it, or we can add it explicitly here.
                    NULL; 
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'indexing_jobs_org_status_idx' AND n.nspname = current_schema()) THEN
                    ALTER INDEX indexing_jobs_org_status_idx RENAME TO idx_job_org_status_idx;
                END IF;
            END
            $$;
            """
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'idx_job_org_created_idx' AND n.nspname = current_schema()) THEN
                    ALTER INDEX idx_job_org_created_idx RENAME TO indexing_jobs_org_created_idx;
                END IF;
            END
            $$;
            """,
            reverse_sql=""
        ),
    ]
