# Generated by Django 5.1.6 on 2026-01-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0106_remove_indexingjob_idx_job_site_status_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='indexingjob',
                    new_name='indexing_jobs_org_status_idx',
                    old_name='idx_job_org_status_idx',
                ),
                migrations.RenameIndex(
                    model_name='indexingjob',
                    new_name='indexing_jobs_org_created_idx',
                    old_name='idx_job_org_created_idx',
                ),
            ]
        )
    ]
