# Generated by Django 4.2.7 on 2026-01-01 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='admin_api_l_user_id_21c0cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(help_text='Stored separately in case admin is deleted', max_length=254)),
                ('action', models.CharField(choices=[('user.view', 'Viewed User'), ('user.update', 'Updated User'), ('user.suspend', 'Suspended User'), ('user.activate', 'Activated User'), ('user.delete', 'Deleted User'), ('user.verify_email', 'Verified Email'), ('user.unverify_email', 'Unverified Email'), ('user.reset_password', 'Triggered Password Reset'), ('user.resend_verification', 'Resent Verification'), ('user.impersonate', 'Impersonated User'), ('org.view', 'Viewed Organization'), ('org.update', 'Updated Organization'), ('org.quota_update', 'Updated Quotas'), ('org.subscription_change', 'Changed Subscription'), ('system.config_change', 'Changed System Config'), ('system.feature_toggle', 'Toggled Feature'), ('bulk.suspend', 'Bulk Suspended Users'), ('bulk.activate', 'Bulk Activated Users'), ('bulk.delete', 'Bulk Deleted Users'), ('export.users', 'Exported Users'), ('export.organizations', 'Exported Organizations')], db_index=True, max_length=50)),
                ('target_type', models.CharField(blank=True, help_text='Type of target: user, organization, etc.', max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='ID of the target object', max_length=100)),
                ('target_label', models.CharField(blank=True, help_text='Human-readable label (email, org name)', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='admin_api_a_admin_i_0e9cf5_idx'), models.Index(fields=['action', 'created_at'], name='admin_api_a_action_57d10f_idx'), models.Index(fields=['target_type', 'target_id'], name='admin_api_a_target__f9a346_idx')],
            },
        ),
    ]
