# Generated by Django 4.2.7 on 2026-01-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_api', '0001_audit_logging'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('alert_type', models.CharField(choices=[('failed_logins', 'Multiple Failed Login Attempts'), ('job_failures', 'Indexing Job Failures'), ('system_health', 'System Health Degradation'), ('quota_exceeded', 'Organization Quota Exceeded'), ('security_event', 'Security Event Detected'), ('high_error_rate', 'High Error Rate'), ('suspicious_activity', 'Suspicious Activity')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text="Alert conditions (e.g., {'threshold': 5, 'time_window_minutes': 10})")),
                ('notification_channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('slack', 'Slack')], default='email', max_length=20)),
                ('notification_target', models.CharField(help_text='Email address, webhook URL, or Slack channel', max_length=500)),
                ('cooldown_minutes', models.IntegerField(default=30, help_text='Minimum minutes between repeated alerts')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Admin2FA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_encrypted_secret', models.BinaryField(db_column='encrypted_secret', help_text='Encrypted TOTP secret key')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for this admin')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has verified their 2FA setup')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Hashed backup codes for recovery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin 2FA',
                'verbose_name_plural': 'Admin 2FA',
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('related_type', models.CharField(blank=True, max_length=50)),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('auto_resolve', models.BooleanField(default=False, help_text='Automatically resolve when condition clears')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Alert expires after this time', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'level'], name='admin_api_s_is_acti_025a94_idx'), models.Index(fields=['created_at'], name='admin_api_s_created_ca99b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_error', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict, help_text='Additional context data about the alert')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admin_api.alertrule')),
            ],
            options={
                'verbose_name': 'Alert Notification',
                'verbose_name_plural': 'Alert Notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['rule', 'sent_at'], name='admin_api_a_rule_id_0fd4b8_idx')],
            },
        ),
    ]
