# Generated by Django 5.1.6 on 2026-01-19 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_add_2fa_and_alerting_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('banner', 'Banner (Top of page)'), ('modal', 'Modal (Popup)'), ('toast', 'Toast (Corner notification)')], default='banner', max_length=20)),
                ('style', models.CharField(choices=[('info', 'Information (Blue)'), ('warning', 'Warning (Yellow)'), ('success', 'Success (Green)'), ('error', 'Error (Red)')], default='info', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='Optional action link')),
                ('link_text', models.CharField(blank=True, help_text='Text for the action link', max_length=100)),
                ('is_dismissible', models.BooleanField(default=True, help_text='Users can dismiss this announcement')),
                ('show_to_all', models.BooleanField(default=True, help_text='Show to all users (otherwise only to specific tiers)')),
                ('target_tiers', models.JSONField(blank=True, default=list, help_text='List of tier names to show to (if not showing to all)')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='When to start showing (immediately if null)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When to stop showing (never if null)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('dismiss_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
