# Generated by Django 5.2.6 on 2025-09-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_create_chatbot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='auto_open',
            field=models.BooleanField(default=False, help_text='Auto-open chat on page load'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='enable_sound_notifications',
            field=models.BooleanField(default=False, help_text='Enable sound notifications'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='enable_typing_indicator',
            field=models.BooleanField(default=True, help_text='Show typing indicator'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='greeting_message',
            field=models.TextField(default='Hello! How can I help you today?', help_text='Initial greeting message', max_length=500),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum connection retry attempts'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='placeholder_text',
            field=models.CharField(default='Type your message...', help_text='Input placeholder text', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='position',
            field=models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', help_text='Widget position on page', max_length=15),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Primary color for widget (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='reconnect_delay',
            field=models.PositiveIntegerField(default=2000, help_text='Reconnection delay in milliseconds'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', help_text='Widget theme', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Chatbot status', max_length=20),
        ),
    ]
