# Generated by Django 4.2.7 on 2025-12-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_widget_configuration'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='chatbot',
        #     name='chatbots_org_id_a5fd6e_idx',
        # ),
        # migrations.RemoveField(
        #     model_name='chatbot',
        #     name='config',
        # ),
        # migrations.RemoveField(
        #     model_name='chatbot',
        #     name='org_id',
        # ),
    ]
