# Generated by Django 4.2.7 on 2025-12-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0102_remove_chatbot_chatbot_site_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual'), ('formal', 'Formal')], default='friendly', help_text='Chatbot conversation tone', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='response_length',
            field=models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], default='balanced', help_text='Preferred response length', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Text color for widget (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Primary/background color for widget (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='Chatbot deployment status', max_length=20),
        ),
    ]
