# Generated by Django 4.2.7 on 2025-12-28 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0103_add_chatbot_personality_and_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationStarter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(help_text='The suggested question text', max_length=500)),
                ('category', models.CharField(blank=True, default='', help_text='Optional category for grouping starters', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this starter is currently active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times this starter has been clicked')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='Whether this was auto-generated from indexed content')),
                ('chatbot', models.ForeignKey(help_text='The chatbot this starter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_starters', to='chatbot.chatbot')),
            ],
            options={
                'verbose_name': 'Conversation Starter',
                'verbose_name_plural': 'Conversation Starters',
                'db_table': 'conversation_starters',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['chatbot', 'is_active'], name='conversatio_chatbot_3ccf3c_idx'), models.Index(fields=['display_order'], name='conversatio_display_015b7a_idx')],
            },
        ),
    ]
