# Generated by Django 4.2.7 on 2025-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0105_add_query_category_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='querycategory',
            new_name='query_categ_chatbot_b375d5_idx',
            old_name='query_categ_chatbot_active_idx',
        ),
        migrations.RenameIndex(
            model_name='querycategory',
            new_name='query_categ_display_2ea82a_idx',
            old_name='query_categ_display_order_idx',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='language',
            field=models.CharField(default='en', help_text="Response language code (e.g., 'en', 'es', 'fr')", max_length=10),
        ),
    ]
