# Generated by Django 4.2.7 on 2026-01-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0106_add_language_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Text color for widget (hex format)', max_length=7),
        ),
    ]
