# Generated by Django 4.2.7 on 2026-01-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0108_change_site_to_fk_cascade'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbots_site_id_6b5072_idx',
        ),
        migrations.RenameIndex(
            model_name='chatbot',
            new_name='chatbots_site_id_6b5072_idx',
            old_name='chatbots_site_fk_idx',
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Widget theme (light or dark)', max_length=10),
        ),
    ]
