# Generated by Django 5.1.6 on 2026-01-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0110_restore_auto_theme_option'),
        ('sites', '0106_alter_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='site',
            field=models.ForeignKey(help_text='Associated knowledge base - chatbots are deleted when knowledge base is deleted', on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='sites.site'),
        ),
    ]
