# Generated by Django 4.2.7 on 2026-01-01 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_membership_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(help_text='Stripe event ID for deduplication', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text="Stripe event type (e.g., 'checkout.session.completed')", max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Raw Stripe event payload for debugging')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Payment Event',
                'verbose_name_plural': 'Payment Events',
                'db_table': 'payment_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='payment_eve_stripe__9ae5b1_idx'), models.Index(fields=['event_type'], name='payment_eve_event_t_62d8ef_idx'), models.Index(fields=['processed'], name='payment_eve_process_5abe21_idx'), models.Index(fields=['organization'], name='payment_eve_organiz_dae292_idx'), models.Index(fields=['created_at'], name='payment_eve_created_0c1f4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_invoice_id', models.CharField(help_text='Stripe invoice ID', max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='open', max_length=50)),
                ('subtotal', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('amount_due', models.IntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('invoice_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['organization'], name='invoices_organiz_d296b0_idx'), models.Index(fields=['stripe_invoice_id'], name='invoices_stripe__83e0c8_idx'), models.Index(fields=['status'], name='invoices_status_07776b_idx'), models.Index(fields=['invoice_date'], name='invoices_invoice_e14adb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_session_id', models.CharField(help_text='Stripe Checkout Session ID', max_length=255, unique=True)),
                ('target_plan', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success_url', models.URLField(max_length=500)),
                ('cancel_url', models.URLField(max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Checkout Session',
                'verbose_name_plural': 'Checkout Sessions',
                'db_table': 'checkout_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='checkout_se_organiz_ed24a5_idx'), models.Index(fields=['stripe_session_id'], name='checkout_se_stripe__53f2ea_idx'), models.Index(fields=['status'], name='checkout_se_status_5a020a_idx'), models.Index(fields=['created_at'], name='checkout_se_created_ea2673_idx')],
            },
        ),
    ]
