# Generated by Django 4.2.7 on 2025-09-08 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField()),
                ('site_id', models.UUIDField(blank=True, null=True)),
                ('chatbot_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('embedding', 'Embedding'), ('query', 'Query'), ('index_write', 'Index Write'), ('chat', 'Chat')], max_length=20)),
                ('units', models.IntegerField(default=1)),
                ('cost_cents', models.IntegerField(default=0)),
                ('meta', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usage Event',
                'verbose_name_plural': 'Usage Events',
                'db_table': 'usage_events',
                'indexes': [models.Index(fields=['org_id'], name='usage_event_org_id_72145c_idx'), models.Index(fields=['type'], name='usage_event_type_f79ba2_idx'), models.Index(fields=['occurred_at'], name='usage_event_occurre_58ffb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('limits', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quotas',
                'db_table': 'quotas',
                'indexes': [models.Index(fields=['org_id'], name='quotas_org_id_d5412d_idx'), models.Index(fields=['period_start', 'period_end'], name='quotas_period__a77eab_idx')],
            },
        ),
    ]
