# Generated by Django 4.2.7 on 2025-12-22 10:02

from django.db import migrations


def remove_indexes_if_exist(apps, schema_editor):
    """Safely remove indexes only if they exist."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            indexes_to_remove = [
                'quota_org_period_idx',
                'quota_period_idx',
                'usage_org_created_idx',
                'usage_org_type_created_idx',
                'usage_site_created_idx',
                'usage_chatbot_created_idx',
                'usage_type_created_idx',
            ]
            for index_name in indexes_to_remove:
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0100_add_performance_indexes'),
    ]

    operations = [
        migrations.RunPython(
            remove_indexes_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
