# Generated by Django 4.2.7 on 2025-12-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0101_remove_quota_quota_org_period_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quota',
            name='quota_org_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='quota',
            name='quota_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='usageevent',
            name='usage_org_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='usageevent',
            name='usage_org_type_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='usageevent',
            name='usage_site_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='usageevent',
            name='usage_chatbot_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='usageevent',
            name='usage_type_created_idx',
        ),
    ]
