# Generated by Django 4.2.7 on 2026-01-03 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_alter_organization_plan_tier'),
        ('usage', '0103_add_subscription_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
        migrations.CreateModel(
            name='UpgradeInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_plan', models.CharField(choices=[('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20)),
                ('source', models.CharField(choices=[('billing_page', 'Billing Page'), ('upgrade_prompt', 'Upgrade Prompt'), ('limit_reached', 'Limit Reached'), ('feature_locked', 'Feature Locked'), ('usage_page', 'Usage Page'), ('other', 'Other')], default='billing_page', max_length=50)),
                ('email', models.EmailField(help_text='Contact email for waitlist notifications', max_length=254)),
                ('company_name', models.CharField(blank=True, help_text='Company name for enterprise inquiries', max_length=255)),
                ('message', models.TextField(blank=True, help_text='Optional message or requirements')),
                ('metadata', models.JSONField(default=dict, help_text='Additional context (current usage, features requested, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for sales/admin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_interests', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upgrade Interest',
                'verbose_name_plural': 'Upgrade Interests',
                'db_table': 'upgrade_interests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='upgrade_int_organiz_cbd023_idx'), models.Index(fields=['interested_plan'], name='upgrade_int_interes_538c04_idx'), models.Index(fields=['status'], name='upgrade_int_status_752869_idx'), models.Index(fields=['created_at'], name='upgrade_int_created_45a9cd_idx')],
            },
        ),
    ]
