# Generated by Django 4.2.7 on 2025-12-31 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_is_active'),
        ('usage', '0102_remove_quota_quota_org_period_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('features_override', models.JSONField(default=dict, help_text='Custom feature toggles that override tier defaults')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('analytics_retention_days', models.IntegerField(blank=True, help_text='Override default retention based on tier', null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['organization'], name='subscriptio_organiz_5780cf_idx'), models.Index(fields=['plan'], name='subscriptio_plan_59e3ed_idx'), models.Index(fields=['status'], name='subscriptio_status_572d44_idx'), models.Index(fields=['trial_ends_at'], name='subscriptio_trial_e_0750ab_idx')],
            },
        ),
    ]
