# Generated by Django 4.2.7 on 2026-01-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0104_alter_subscription_plan_upgradeinterest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['org_id', 'type', 'occurred_at'], name='usage_events_quota_idx'),
        ),
    ]
