# Generated by Django 4.2.7 on 2025-12-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawa_auth', '0002_emailverification_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration date for the API key', null=True),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['expires_at'], name='api_keys_expires_f68b1a_idx'),
        ),
    ]
