# Generated by Django 4.2.7 on 2025-12-22 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lawa_auth', '0005_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField(blank=True, help_text='Organization context if applicable', null=True)),
                ('category', models.CharField(choices=[('account', 'Account & Billing'), ('technical', 'Technical Issue'), ('feature', 'Feature Request'), ('other', 'Other')], help_text='Request category', max_length=20)),
                ('subject', models.CharField(help_text='Brief summary of the issue', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the request')),
                ('page_url', models.CharField(blank=True, help_text='Page where request was submitted', max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent', max_length=500, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting for User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from support staff', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the request was resolved', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'db_table': 'support_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='support_req_user_id_a005cb_idx'), models.Index(fields=['org_id'], name='support_req_org_id_d7070e_idx'), models.Index(fields=['status'], name='support_req_status_ba7e97_idx'), models.Index(fields=['priority'], name='support_req_priorit_33fc04_idx'), models.Index(fields=['category'], name='support_req_categor_7d1fe6_idx'), models.Index(fields=['created_at'], name='support_req_created_5a6f17_idx')],
            },
        ),
    ]
