# Generated by Django 4.2.7 on 2026-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawa_auth', '0006_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='actual_behavior',
            field=models.TextField(blank=True, help_text='What actually happened', null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='expected_behavior',
            field=models.TextField(blank=True, help_text='What was expected to happen', null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='screen_resolution',
            field=models.CharField(blank=True, help_text='Screen resolution', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, help_text='Steps to reproduce the bug', null=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(choices=[('general', 'General Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('billing', 'Billing'), ('account', 'Account'), ('technical', 'Technical Support')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='description',
            field=models.TextField(help_text='Detailed description of the issue'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(help_text='Issue summary', max_length=255),
        ),
    ]
