# Generated by Django 4.2.7 on 2025-09-08 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField()),
                ('chatbot_id', models.UUIDField()),
                ('site_id', models.UUIDField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('meta', models.JSONField(default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
                'indexes': [models.Index(fields=['org_id'], name='chat_sessio_org_id_a99491_idx'), models.Index(fields=['chatbot_id'], name='chat_sessio_chatbot_15800d_idx'), models.Index(fields=['site_id'], name='chat_sessio_site_id_39b307_idx'), models.Index(fields=['session_key'], name='chat_sessio_session_d8342f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('citations', models.JSONField(default=list)),
                ('latency_ms', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['session'], name='chat_messag_session_70d2c0_idx'), models.Index(fields=['role'], name='chat_messag_role_ddd811_idx'), models.Index(fields=['created_at'], name='chat_messag_created_eb4133_idx')],
            },
        ),
    ]
