# Generated by Django 4.2.7 on 2025-12-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0101_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatfeedback',
            name='chat_feedback_msg_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatfeedback',
            name='chat_feedback_msg_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatfeedback',
            name='chat_feedback_type_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_msg_sess_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_msg_sess_role_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_msg_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sess_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sess_org_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sess_bot_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sess_site_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sess_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sess_status_activity_idx',
        ),
    ]
