# Generated by Django 6.0 on 2025-12-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0103_add_geo_and_category_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_query_c_82a675_idx',
            old_name='chat_messag_category_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_query_c_17bab1_idx',
            old_name='chat_messag_cat_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_sessio_geo_cou_75a22c_idx',
            old_name='chat_sessio_geo_country_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_sessio_geo_cou_d65e5a_idx',
            old_name='chat_sessio_geo_region_idx',
        ),
    ]
