# Generated by Django 4.2.7 on 2025-09-15 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField(help_text='Organization identifier')),
                ('site_id', models.UUIDField(help_text='Site identifier')),
                ('name', models.CharField(help_text='Chatbot name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Chatbot description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', help_text='Chatbot status', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Chatbot configuration (model, temperature, etc.)')),
                ('embed_code', models.TextField(blank=True, help_text='Embed code for website')),
                ('api_key', models.CharField(help_text='API key for chatbot access', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'db_table': 'chatbots',
                'indexes': [models.Index(fields=['org_id'], name='chatbots_org_id_a5fd6e_idx'), models.Index(fields=['site_id'], name='chatbots_site_id_6b5072_idx'), models.Index(fields=['status'], name='chatbots_status_b39a38_idx'), models.Index(fields=['api_key'], name='chatbots_api_key_bae025_idx')],
            },
        ),
    ]
