# Generated by Django 4.2.7 on 2025-12-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatbot_chatbots_org_id_a5fd6e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbots_org_id_a5fd6e_idx',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='config',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='org_id',
        ),
    ]
