# Generated by Django 6.0 on 2025-12-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chatbot_chatbots_org_id_a5fd6e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='AI Behavior Config (model, prompt, temperature)'),
        ),
    ]
