# Generated by Django 4.2.7 on 2025-12-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0101_remove_chatbot_chatbot_site_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_site_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_site_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_api_key_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_active_site_created_idx',
        ),
    ]
