# Generated by Django 4.2.7 on 2026-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0109_update_theme_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='Widget theme (light, dark, or auto for system preference)', max_length=10),
        ),
    ]
