# Generated by Django 4.2.7 on 2025-09-08 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['status'], name='outbox_even_status_90eac7_idx'), models.Index(fields=['scheduled_at'], name='outbox_even_schedul_b8d1ab_idx'), models.Index(fields=['created_at'], name='outbox_even_created_dc5a3b_idx')],
            },
        ),
    ]
